ALTER TABLE coupon
    CHANGE COLUMN stock total_quantity INT NOT NULL,
    ADD COLUMN start_at TIMESTAMP NULL,
    ADD COLUMN end_at TIMESTAMP NULL,
    ADD COLUMN status ENUM('READY', 'OPEN', 'CLOSE') NOT NULL DEFAULT 'READY',
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP;